stages:
  - stage: Build
    displayName: 'Build and push image'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true 
            clean: true   
            lfs: true
            fetchDepth: 0

          # Set up Docker image name
          - script: |
              echo "##vso[task.setvariable variable=IMAGE_NAME]$(DOCKER_IMAGE)"
            displayName: 'Set up Docker image name'

          # Update Dockerfile to use the specified image name
          - script: |
              sed -i "s|^FROM .*|FROM $(IMAGE_NAME)|" Dockerfile
              cat Dockerfile
            displayName: 'Update Dockerfile'

          # Build and push the Docker image
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: '$(CONTAINERREGISTRY_NAME)'
              repository: '$(IMAGE_NAME)'
              dockerfile: 'Dockerfile'
              command: 'buildAndPush'
              tags: '$(TAG)'
