trigger:
  - none
pr: none

resources:
  - repo: self

variables:  
  TAG: '$(Build.SourceVersion)'

stages:
  - stage: BuildandPush
    displayName: 'Build and push image'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Push image to Docker Hub'
            inputs:
              containerRegistry: '$(CONTAINERREGISTRY_NAME)'
              repository: '$(IMAGE_NAME)'
              command: 'buildAndPush'
              tags: '$(TAG)'
