apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  namespace: argo-app
spec:
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
      - name: argo-app
        image: vimalr/argo-app:latest
        ports:
        - containerPort: 80


