apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  labels:
    app: argo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
      - name: argo-app
        image: vimalr/argo-app:7e186f356cf1d2334c177ffcd1682c2501994682
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

