apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  labels:
    app: argo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
      - name: argo-app
        image: vimalr/argo-app:c896f375f9b1065f8681c4cc6bac1621666daba9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

