apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: githubactions-aks-demo-ingress-service
  #annotations:
   # kubernetes.io/ingress.class: nginx  
spec:  
  ingressClassName: nginx
  rules:
    - host: tvlcloud.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: githubactions-aks-demo-service
                port: 
                  number: 80
              

  
