name: Trigger auto deployment for acanginx

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/acanginx-AutoDeployTrigger-85602968-dd3a-43ff-91e4-255de3423e32.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACANGINX_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: aca0001.azurecr.io
          registryUsername: ${{ secrets.ACANGINX_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACANGINX_REGISTRY_PASSWORD }}
          containerAppName: acanginx
          resourceGroup: vimal001
          imageToBuild: aca0001.azurecr.io/acanginx:${{ github.sha }}
          
      - name: Get container apps properties
        run: |
          output=$(az containerapp show --name acanginx --resource-group vimal001)
          provisioningState=$(echo $output | jq -r '.properties.provisioningState')
          runningStatus=$(echo $output | jq -r '.properties.runningStatus')
          if [ "$provisioningState" != "Succeeded" ] || [ "$runningStatus" != "Running" ]; then
            echo "Error: Provisioning state is not 'Succeeded' or running status is not 'Running'."
            exit 1
          fi
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
            

     

