name: Build and Update GitOps

on:
  push:
    branches: [ "argo-cd" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set IMAGE TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          docker build -t vimalr/argo-app:${{ env.IMAGE_TAG }} .
          docker push vimalr/argo-app:${{ env.IMAGE_TAG }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: vimalprasathr/nginx-aca
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops

      - name: Update image tag in GitOps repo
        run: |
          sed -i "s|image: vimal/argo-app:.*|image: vimalr/argo-app:${{ env.IMAGE_TAG }}|g" k8s/deployment.yaml

      - name: Create PR to GitOps repo
        uses: peter-evans/create-pull-request@v5
        with:
          path: gitops
          branch: update-image-${{ env.IMAGE_TAG }}
          commit-message: "Update image tag to ${{ env.IMAGE_TAG }}"
          title: "Update image tag to ${{ env.IMAGE_TAG }}"
          body: "Auto updating image to ${{ env.IMAGE_TAG }}"
