name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "vimal0001.azurecr.io"
  CONTAINER_NAME: "githubactions-aks-demo"
  RESOURCE_GROUP: "vimal-rg"
  CLUSTER_NAME: "vimall001"
  DEPLOYMENT_MANIFEST_PATH: "deploy.yaml"

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image $AZURE_CONTAINER_REGISTRY.azurecr.io/$CONTAINER_NAME:${{ github.sha }} --registry $AZURE_CONTAINER_REGISTRY -g $RESOURCE_GROUP .

  deploy:
    runs-on: ubuntu-latest
    needs: [buildImage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v1.0.0'

      - name: Get K8s context
        uses: azure/aks-set-context@v1
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: $CLUSTER_NAME
          resource-group: $RESOURCE_GROUP

      - name: Deploys application
        uses: Azure/k8s-deploy@v1
        with:
          action: 'deploy'
          manifests: $DEPLOYMENT_MANIFEST_PATH
          images: |
            $AZURE_CONTAINER_REGISTRY.azurecr.io/$CONTAINER_NAME:${{ github.sha }}
