name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]

env:
  IMAGE_NAME: vimalr/buildtest
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy to Dev
        run: |
          echo $IMAGE_TAG
          #helm upgrade --install myapp-dev ./helm \
          #  --set image.repository=$IMAGE_NAME \
          #  --set image.tag=$IMAGE_TAG \
          #  --namespace dev
