name: Mirror Active Branch to Azure DevOps

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  mirror:
    name: Mirror pushed branch to Azure DevOps
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        id: extract
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.extract.outputs.branch_name }}

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Validate Azure DevOps credentials
        run: |
          if [ -z "${{ secrets.AZURE_USERNAME }}" ] || [ -z "${{ secrets.AZURE_PAT }}" ]; then
            echo "Azure DevOps credentials are missing. Please set AZURE_USERNAME and AZURE_PAT secrets."
            exit 1
          fi

      - name: Add Azure DevOps remote
        run: |
          git remote add azure https://${{ secrets.AZURE_USERNAME }}:${{ secrets.AZURE_PAT }}@dev.azure.com/vimal-playground/github-mirror-h/_git/github-mirror-h

      - name: Push current branch to Azure DevOps
        run: |
          git push azure ${{ steps.extract.outputs.branch_name }} --force

      - name: Push tags to Azure DevOps
        run: |
          git push azure --tags
