name: Docker Build and TrivyScan

on:
  push:
    branches:
      - Trivy-Image-Scan-GA  # Adjust this according to your branch name

jobs:
  build-and-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        touch .env
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
        BUILD_DATE=$(date "+%d%m%Y")
        BUILD_TIME=$(date "+%H%M%S")
        BUILD_NUMBER="${BUILD_NUMBER}"
        VERSION="${BUILD_DATE}.${BUILD_TIME}-${BUILD_NUMBER}"
        echo "version=${VERSION}" >> .env
        cat .env
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }} .
      env:
        BUILD_NUMBER: ${{ github.run_number }}

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Trivy Scan Docker Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}
        format: 'table'  # Display in table format
        exit-code: 0     # Continue workflow even if vulnerabilities are found
        ignore-unfixed: true  # Only show vulnerabilities with available fixes

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}
